# Nom du microservice
spring.application.name=commande
server.port=8083

# ===============================
# H2 DATABASE
# ===============================
spring.datasource.url=jdbc:h2:mem:commande
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# Eureka Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===============================
# Feign (optionnel mais recommandé)
# ===============================
feign.hystrix.enabled=true