server.port=8082

spring.application.name=ContractService

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/contract_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# EUREKA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ?? Feign + Resilience4j bridge ???????????????????????????????????????????????
feign.circuitbreaker.enabled=true

# ?? Circuit Breaker ???????????????????????????????????????????????????????????
resilience4j.circuitbreaker.instances.propertyService.sliding-window-size=10
resilience4j.circuitbreaker.instances.propertyService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.propertyService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.propertyService.permitted-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.propertyService.register-health-indicator=true
resilience4j.circuitbreaker.instances.propertyService.automatic-transition-from-open-to-half-open-enabled=true

# ?? Retry ?????????????????????????????????????????????????????????????????????
resilience4j.retry.instances.propertyService.max-attempts=3
resilience4j.retry.instances.propertyService.wait-duration=500ms
resilience4j.retry.instances.propertyService.retry-exceptions=feign.FeignException

# ?? TimeLimiter ???????????????????????????????????????????????????????????????
resilience4j.timelimiter.instances.propertyService.timeout-duration=3s
resilience4j.timelimiter.instances.propertyService.cancel-running-future=true

# ?? Actuator ??????????????????????????????????????????????????????????????????
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true