server.port=8082

spring.application.name=ContractService

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/contract_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# EUREKA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# RESILIENCE4J
resilience4j.circuitbreaker.instances.propertyService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.propertyService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.propertyService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.propertyService.waitDurationInOpenState=10s

resilience4j.retry.instances.propertyService.maxAttempts=3
resilience4j.retry.instances.propertyService.waitDuration=1s

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html