server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/contract_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Resilience4j
resilience4j.circuitbreaker.instances.propertyService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.propertyService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.propertyService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.propertyService.waitDurationInOpenState=10s

resilience4j.retry.instances.propertyService.maxAttempts=3
resilience4j.retry.instances.propertyService.waitDuration=1s

# ACTUATOR
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.endpoint.health.show-details=always