# Config spécifique au service Order
spring.data.mongodb.uri=mongodb+srv://yosr:12345@cluster1.gddxkmk.mongodb.net/orderdb?retryWrites=true&w=majority
spring.data.mongodb.database=orderdb

eureka.instance.prefer-ip-address=true