global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'property-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['property-service:8081']

  - job_name: 'contract-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['contract-service:8082']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8083']