server.port=8080
spring.application.name=Proxy-Service

# =========================
# EUREKA
# =========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1

# =========================
# GATEWAY CONFIG
# =========================
spring.main.web-application-type=reactive
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.gateway.discovery.locator.enabled=false

# =========================
# PROPERTY SERVICE
# =========================
spring.cloud.gateway.routes[0].id=property-service
spring.cloud.gateway.routes[0].uri=lb://PROPERTY-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/property-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# =========================
# CONTRACT SERVICE
# =========================
spring.cloud.gateway.routes[1].id=contract-service
spring.cloud.gateway.routes[1].uri=lb://CONTRACTSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/contract-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# =========================
# PAYMENT SERVICE
# =========================
spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/payment-service/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# =========================
# AUTH SERVICE
# =========================
spring.cloud.gateway.routes[3].id=auth-service
spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1