server.port=8080
spring.application.name=Proxy-Service

spring.config.import=optional:configserver:http://localhost:8888

# =========================
# EUREKA
# =========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# =========================
# GATEWAY CONFIG
# =========================
spring.main.web-application-type=reactive
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.gateway.discovery.locator.enabled=false

# =========================
# PROPERTY SERVICE
# =========================
spring.cloud.gateway.routes[0].id=property-service
spring.cloud.gateway.routes[0].uri=lb://Property-Service
spring.cloud.gateway.routes[0].predicates[0]=Path=/property-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Swagger UI Property Service
spring.cloud.gateway.routes[1].id=property-swagger-ui
spring.cloud.gateway.routes[1].uri=lb://Property-Service
spring.cloud.gateway.routes[1].predicates[0]=Path=/property-service/swagger-ui/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=property-api-docs
spring.cloud.gateway.routes[2].uri=lb://Property-Service
spring.cloud.gateway.routes[2].predicates[0]=Path=/property-service/v3/api-docs/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# =========================
# CONTRACT SERVICE
# =========================
spring.cloud.gateway.routes[3].id=contract-service
spring.cloud.gateway.routes[3].uri=lb://ContractService
spring.cloud.gateway.routes[3].predicates[0]=Path=/contract-service/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[4].id=contract-swagger-ui
spring.cloud.gateway.routes[4].uri=lb://ContractService
spring.cloud.gateway.routes[4].predicates[0]=Path=/contract-service/swagger-ui/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[5].id=contract-api-docs
spring.cloud.gateway.routes[5].uri=lb://ContractService
spring.cloud.gateway.routes[5].predicates[0]=Path=/contract-service/v3/api-docs/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

# =========================
# PAYMENT SERVICE
# =========================
spring.cloud.gateway.routes[6].id=payment-service
spring.cloud.gateway.routes[6].uri=lb://payment-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/payment-service/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[7].id=payment-swagger-ui
spring.cloud.gateway.routes[7].uri=lb://payment-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/payment-service/swagger-ui/**
spring.cloud.gateway.routes[7].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[8].id=payment-api-docs
spring.cloud.gateway.routes[8].uri=lb://payment-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/payment-service/v3/api-docs/**
spring.cloud.gateway.routes[8].filters[0]=StripPrefix=1

# =========================
# AUTH SERVICE
# =========================
spring.cloud.gateway.routes[9].id=auth-service
spring.cloud.gateway.routes[9].uri=lb://auth-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.routes[9].filters[0]=StripPrefix=1