server.port=8080

spring.application.name=Proxy-Service

# =========================
# EUREKA
# =========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# =========================
# CONFIG GENERAL
# =========================
spring.main.web-application-type=reactive
spring.cloud.compatibility-verifier.enabled=false


spring.cloud.gateway.server.webflux.discovery.locator.enabled=false
spring.cloud.gateway.server.webflux.routes[0].id=property-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://Property-Service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/property-service/properties/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# ROUTE CONTRACT SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=contract-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://Contract-Service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/contract-service/contracts/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1