server.port=8761
spring.application.name=discovery-service
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.server.enableSelfPreservation=false

spring.cloud.compatibility-verifier.enabled=false

